### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by lidaof** [4dn-dcic/hic2cool#15]
Would like to report another issue, thanks
<pre>
$ hic2cool GSE63525_IMR90_combined_30.hic GSE63525_IMR90_combined_30.cool
################
################
hic file header info:
Chromosomes:  [u'All', u'chr1', u'chr2', u'chr3', u'chr4', u'chr5', u'chr6', u'chr7', u'chr8', u'chr9', u'chr10', u'chr11', u'chr12', u'chr13', u'chr14', u'chr15', u'chr16', u'chr17', u'chr18', u'chr19', u'chr20', u'chr21', u'chr22', u'chrX', u'chrY', u'chrM']
Resolutions:  [2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000]
Genome:  hg19
Traceback (most recent call last):
  File "/opt/apps/python2/bin/hic2cool", line 11, in <module>
    sys.exit(main())
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/__main__.py", line 46, in main
    args.normalization, args.exclude_MT, True)
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/hic2cool_utils.py", line 769, in hic2cool_convert
    chr_footer_info, bin_map, count_map)
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/hic2cool_utils.py", line 404, in parse_hic
    c2Norm = read_normalization_vector(req, chr_footer_info[c2])
KeyError: 9

</pre>

**Comment by carlvitzthum** [comment]
Please see #14
