### ISSUE TITLE
hic2cool update

### ISSUE THREAD

**Issue by imerelli** [4dn-dcic/hic2cool#29]
Hi, hic2cool update is not working for me (both specifying the output or not). The software ask  yes/no for writing, but in both cases it raises an error. Here the error:

```
$ hic2cool -v
hic2cool 0.6.0

$ hic2cool update inter_30.mcool 
#########################
### hic2cool / update ###
#########################
### Info from input file
... File path: inter_30.mcool
... Found creation timestamp: 2019-05-03 at 16:07:31
... Found update timestamp: None
... Found resolutions: [u'10000', u'100000', u'1000000', u'25000', u'250000', u'2500000', u'5000', u'50000', u'500000']
... Found version: 0.5.1
... Target version: 0.6.0
### Updates found. Will upgrade hic2cool file to version 0.6.0
### This is what will change:
- Add cooler schema version
    - Effect: Add a couple important cooler schema attributes
    - Detail: Adds format-version and storage-mode attributes to hdf5 for compatibility with cooler schema v3.
### Will write to inter_30.mcool
### Continue? [y/n]
[y/n] y
Traceback (most recent call last):
  File "/bin/hic2cool", line 9, in <module>
    load_entry_point('hic2cool==0.6.0', 'console_scripts', 'hic2cool')()
  File "build/bdist.linux-x86_64/egg/hic2cool/__main__.py", line 82, in main
  File "build/bdist.linux-x86_64/egg/hic2cool/hic2cool_utils.py", line 1204, in hic2cool_update
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```

**Comment by carlvitzthum** [comment]
Hi @imerelli

Thank you for reporting this issue. It was due to a python 2/3 incompatibility and should currently work with Python3. I will work on a fix for python 2 and keep you updated.

**Comment by imerelli** [comment]
Honestly I have problems also with python3

```
$ python --version
Python 3.6.6
$ hic2cool -v
hic2cool 0.6.0
$ hic2cool update inter_30.mcool_old 
#########################
### hic2cool / update ###
#########################
Traceback (most recent call last):
  File "/opt/anaconda3/bin/hic2cool", line 11, in <module>
    load_entry_point('hic2cool==0.6.0', 'console_scripts', 'hic2cool')()
  File "/opt/anaconda3/lib/python3.6/site-packages/hic2cool-0.6.0-py3.6.egg/hic2cool/__main__.py", line 82, in main
  File "/opt/anaconda3/lib/python3.6/site-packages/hic2cool-0.6.0-py3.6.egg/hic2cool/hic2cool_utils.py", line 1178, in hic2cool_update
TypeError: strptime() argument 1 must be str, not bytes

**Comment by carlvitzthum** [comment]
This is likely because you originally created `inter_30.mcool_old` using hic2cool with python 2. I will add a quick fix for that as well.
