### ISSUE TITLE
 Error -3 while decompressing data

### ISSUE THREAD

**Issue by chenggang108** [4dn-dcic/hic2cool#45]
Hi 
I am trying to convert .hic file to mcool.  It show error. Here is how it looks.
 Header info from hic
... Chromosomes:  ['ALL', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5'                                                , '6', '7', '8', '9', 'M', 'X', 'Y']
... Resolutions:  [2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000]
... Normalizations:  ['VC', 'VC_SQRT', 'KR']
... Genome:  /usr/local/apps/hicpro/2.11.1/annotation/chrom_mm10.sizes
### Converting
... Resolution 2500000 took: 18.117652416229248 seconds.
... Resolution 1000000 took: 13.354706525802612 seconds.
... Resolution 500000 took: 48.48037791252136 seconds.
... Resolution 250000 took: 139.53048062324524 seconds.
multiprocessing.pool.RemoteTraceback:
""
Traceback (most recent call last):
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/multiprocessing/pool.                                                                                py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/site-packages/hic2coo                                                                                l/hic2cool_utils.py", line 379, in build_counts_chunk
    records = read_block(req, block_record)
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/site-packages/hic2coo                                                                                l/hic2cool_utils.py", line 232, in read_block
    _uncompressedBytes = zlib.decompress(compressedBytes)
zlib.error: Error -3 while decompressing data: too many length or distance sy                                                                                mbols_
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/chengg2/conda/envs/hic2cool/bin/hic2cool", line 8, in <module>
    sys.exit(main())
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/site-packages/hic2coo                                                                                l/__main__.py", line 86, in main
    hic2cool_convert(args.infile, args.outfile, args.resolution, args.nproc,                                                                                 args.warnings, args.silent)
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/site-packages/hic2coo                                                                                l/hic2cool_utils.py", line 940, in hic2cool_convert
    used_chrs, show_warnings)
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/site-packages/hic2coo                                                                                l/hic2cool_utils.py", line 361, in parse_hic
    result_all.extend(mpi_result[mpi].get())
  File "/data/chengg2/conda/envs/hic2cool/lib/python3.6/multiprocessing/pool.                                                                                py", line 644, in get
    raise self._value
zlib.error: Error -3 while decompressing data: too many length or distance sy                                                                                mbols

**Comment by SooLee** [comment]
Have you checked the hic file is correct and not corrupt?

**Comment by chenggang108** [comment]
Hi Lee,

The .hic file shows perfect matrix in juicebox.

**Comment by SooLee** [comment]
Are you using multi-processing?

**Comment by chenggang108** [comment]
That's something I am trying now. It looks going further. Thank you for your answer. I will let you know

**Comment by SooLee** [comment]
@chenggang108 How did it go?

**Comment by chenggang108** [comment]
@SooLee Sorry for the delay. Multi-processing works

**Comment by SooLee** [comment]
Great. Thanks!
